apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qwnx2hqfn-python
  janus-idp.io/tekton: qwnx2hqfn-python
  backstage.io/kubernetes-id: qwnx2hqfn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qwnx2hqfn-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
