apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qwnx2hqfn-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:4c2fa27f654f03d63d75ca9c092889956dfd993b@sha256:27b3751684eae273e0e319714b5195d5c5a59a96ec88daee529d9a773cd2b32c
          name: container-image
